### ISSUE TITLE
Translations status

### ISSUE THREAD

**Issue by zezinho42** [sergiomb2/pinball#18]
hi, I have tried to use the french translation, but make_install did not install any mo file. Are translations usable as of version 0.3.3.3 ?

Thanks

**Comment by sergiomb2** [comment]
good question , the first 2 commits to have translations are here [1] and the first commit is very intrusive I have to review it ... (I accepted because was in rzr repo ...) .
Conclusion no , not even installed or packaged .

[1] https://github.com/sergiomb2/pinball/commits/devel/data/locale

**Comment by sergiomb2** [comment]
@c30zD how we load a different locale ? do you know how to ?

**Comment by c30zD** [comment]
I just figured it out! Although it's not the solution I was hoping for, at least it works:

1. Create a folder to store the locale files. I used:
`mkdir -p $HOME/.local/share/locale/<language code>/LC_MESSAGES`
2. Copy the *.mo file to the previous folder, but make sure it's called `pinball.mo`
3. Run configure with option `--with-localization-prefix=$HOME/.local/share/locale` (or whatever folder you used), then `make && make install`
4. Set the environment variable LANGUAGE to the language you want to use, e.g. in bash: `export LANGUAGE=<language code>`
5. Run pinball

If deemed necessary, for the folder and variable, the country code could be added, separated by an underscore, i.e. `<language code>_<country code>`.

Make sure you're compiling/installing from a different terminal than you're testing. Is not something very important, but if you wish to recompile in the same terminal that you're using for testing, then some messages from the compiler might get translated.

**Comment by c30zD** [comment]
Okay, now I know the best way (similar to the previous example, but without the need to configure with extra options):

1. Create a folder to store the locale files:
`mkdir -p $HOME/.local/share/locale/<language code>/LC_MESSAGES`
2. Copy the *.mo file to the previous folder, but make sure it's called `pinball.mo`
3. Export variable LANGUAGE like this (in bash):
`export LANGUAGE=../../../$HOME/.local/share/locale/<language code>:<language code>` (notice that between the two language codes there is a colon)
4. Run pinball

_Edit_: I forgot to write the step for copying the *.mo file

**Comment by c30zD** [comment]
Oh, and, as it stands, I think translations are not installed. There is a script in `data/locale` (well, two scripts) to update the German translations, which at the end would copy `pinball_de_DE.mo` to `/usr/share/locale/de_DE/LC_MESSAGES/pinball.mo` (or the UTF-8 equivalent)

**Comment by sergiomb2** [comment]
hum , and what we need todo to  `make install` install it ?

**Comment by c30zD** [comment]
Sadly, I don't know. Right now I don't have too much time to work on this, but I have found that the `gettext` manual has information on it (in the "maintainers" section): https://www.gnu.org/software/gettext/manual/html_node/Maintainers.html#Maintainers. It's also on their texinfo manual, if you have it.

As a side-note, for CMake there is this: https://cmake.org/cmake/help/v3.0/module/FindGettext.html

**Comment by sergiomb2** [comment]
@c30zD OK Thanks , I also haven't much time to  work on this

**Comment by sergiomb2** [comment]
I finished it  , but crash when load pt or Fr , works with en and ge !

**Comment by zezinho42** [comment]
Please explain the crash, it works for me in pt and fr?

**Comment by sergiomb2** [comment]
Hi, 

> Please explain the crash, it works for me in pt and fr?

Sorry I forgot to say that I already fixed it , it was about sentences with more 35 characters [1] 

Btw arrows should be translate to "setas" and not "flechas"  😃  in Portuguese 

[1]  https://github.com/sergiomb2/pinball/commit/adc99498a3ccc5bace0e0cb8cf954da026f5004b

**Comment by zezinho42** [comment]
I knew I would mess something ;-)
So it is ready to make a new release?

**Comment by sergiomb2** [comment]
but you may fix it ? please . 
Aqui está a correção [1] o codigo rebentava quando havia frases com mais de 35 letras ... as frases parecem-me muito grandes , se conseguisses fazer quebras de linhas era excelente

[1]
https://github.com/sergiomb2/pinball/commit/4c4da24369b8be07f188ba8846f83114347b494e

**Comment by sergiomb2** [comment]
> So it is ready to make a new release?

* SDL2 yet need some refresh when change settings for example
* I'd like merge background board of professor table to table2 

this is what I'd like to do before release ...

**Comment by zezinho42** [comment]
For long sentences, I will fix them.

**Comment by zezinho42** [comment]
Version 3.4 fixed this bug
